#!/bin/bash
sh /usr/bin/mysqld_safe &
sleep 10
mysql -u admin -p --password=admin -h localhost < /tmp/mysql_config
mysql --user='admin' --password='admin' --execute='SHOW DATABASES;'
python /etc/rmon/start.py

#while true
#do 
#    echo "alive"
#    sleep 5
#done
